### PR TITLE
Working integration tests on Scala 2.13

### PR DESCRIPTION
**Pull request by martijnblankestijn**

### CODE REVIEW

**Comment by martijnblankestijn** [comment]
I'm in the middle of the process of migrating to Kamon 2.0 and are interested in the Scala 2.13 version of the JMX collector to collect the Kafka metrics.

Made some changes to get it running on Scala 2.13, which also included the upgrade to Kafka 2.4.1 as this is the first branch with Scala 2.13 support. I noticed some changes in the test cases.
First is the name of the consumer group, I just assume that this has to to with the change of the Kafka version.
Second is the order of the string that are expected, I see that sometimes the order was reversed. Did not seem important to me, so I made the verification a bit more lenient with regard to the order of the attributes.

**Comment by robvadai** [comment]
Hi @martijnblankestijn, thank you for the PR.

I'll take a look shortly. Can I ask you to bump the version of the library please.
This we can regard as a minor version change as Scala 2.13 is a new feature.

**Comment by martijnblankestijn** [comment]
Bumped the version to the next RC (2) or was it your preference to go for 1.0.1?

**Comment by robvadai** [comment]
Let's keep it as RC2 given we didn't have enough feedback to officially release 1.0.0 yet.
I'll take a look at the PR hopefully in the next few days, sorry I was quite busy recently.

**Comment by martijnblankestijn** [comment]
> Let's keep it as RC2 given we didn't have enough feedback to officially release 1.0.0 yet.
> I'll take a look at the PR hopefully in the next few days, sorry I was quite busy recently.

Know the feeling ;-)

**Comment by martijnblankestijn** [comment]
Any progress?

**Comment by robvadai** [comment]
@martijnblankestijn thanks for the nudge, merged :)

**Pull request merged**
