### PR TITLE
crosscompile

### LINKED ISSUE #20: Publish for scala 2.11
Any change of publishing this library for scala 2.11?

### PR DESCRIPTION
**Pull request by jtjeferreira**
fixes #20

### CODE REVIEW

**Comment by jtjeferreira** [comment]
I managed to `publishToMavenLocal` and use the scala 2.11 version locally...

**Comment by robvadai** [comment]
Thank you for the PR!
Would you mind also updating the version in `gradle.properties` and in the README?

So change this line: `version = 0.1.5`

This is a feature enhancement and according to semantic versioning probably we should bump the minor version, so use `0.2.0` ? What do you think?

**Comment by jtjeferreira** [comment]
In a perfect world (i.e reproducible builds), we could just republish the current version for Scala 2.11... In the real world this might no be possible...

I am no expert in the semantic versioning spec, but this does not seem a feature enhancement, but something more like a dependencies bump. Also semantic versioning is less restrictive for software still in the 0.x.x range... But whatever works for you, works for me :)

**Comment by robvadai** [comment]
I know what you mean, I just thought this would end up as a new binary so we should not republish the 2.12 version already there. Thanks for the work, I'll merge it and publish it.

**Pull request merged**
