### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by jtjeferreira**
Just to make sure integration tests are okay in master...

### CODE REVIEW

**Comment by jtjeferreira** [comment]
Hi @robvadai! I dont know how to make the integration tests pass...

**Comment by robvadai** [comment]
Sure, I'll take a look at the tests.
This week is pretty hectic for me but I'll try to have a look.

**Comment by manuelcueto** [comment]
I've seen on travis that the build failed but somehow  travis is no returning the status here. Can it be re-triggered? if i run integration tests locally it takes around 35 seconds to pass so maybe 1 minute for patience config is a bit tight for travis?

**Comment by robvadai** [comment]
Build fixed, new version `1.0.0-RC1` released

**Pull request closed without merging**
